version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Loja_01
      SPRING_DATASOURCE_USERNAME: AdminLoja01
      SPRING_DATASOURCE_PASSWORD: AdminLoja01
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./docker/backend_data:/path/to/backend/data # Ajuste o caminho conforme necessário

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AdminLoja01
      MYSQL_DATABASE: Loja_01
      MYSQL_USER: AdminLoja01
      MYSQL_PASSWORD: AdminLoja01
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql

volumes:
  mysql_data: # Este volume seria necessário que você deseje usar volumes nomeados